import {
  BrandSettings,
  ContentItem,
  NotificationRule,
  SocialConnection,
  SocialEvent,
  AuditLog,
  AnalyticsSnapshot,
} from "@/types";

export const initialConnections: SocialConnection[] = [
  {
    id: "conn-gh",
    provider: "github",
    accountName: "mani-538",
    accountId: "gh_u_948210",
    status: "disconnected",
    allowedScopes: ["repo", "read:org", "workflow", "read:user"],
    encryptedTokenPlaceholder: "enc_vault_gh_tok_a8f93...ready",
    capabilities: [
      "Repository activity streaming",
      "Pull request triage & review suggestions",
      "Issue comment drafting",
      "Automated release notes drafting",
      "Cryptographic webhook verification (HMAC-SHA256)",
    ],
    webhookSupported: true,
    pollingFallback: true,
    avatarUrl: "https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "conn-li",
    provider: "linkedin",
    accountName: "Mani Shankar",
    accountId: "li_urn_pers_84719",
    status: "disconnected",
    allowedScopes: ["openid", "profile", "w_member_social", "r_organization_social"],
    encryptedTokenPlaceholder: "enc_vault_li_tok_991c2...ready",
    capabilities: [
      "Personal thought leadership post publishing (approval-required)",
      "Company/organization page management",
      "Post engagement & commentary sync",
      "Inbound message notification triage",
      "Official 2-legged/3-legged OAuth v2 compliance",
    ],
    webhookSupported: true,
    pollingFallback: true,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "conn-ig",
    provider: "instagram",
    accountName: "@signalnest.hq",
    accountId: "ig_biz_178414",
    status: "disconnected",
    allowedScopes: ["instagram_basic", "instagram_manage_comments", "instagram_manage_messages", "pages_show_list"],
    encryptedTokenPlaceholder: "enc_vault_ig_meta_01a...ready",
    capabilities: [
      "Professional business account content publishing",
      "Carousel & reel media metadata synchronization",
      "Direct message lead detection",
      "Comment moderation & suggested reply dispatch",
      "Meta Graph API insights",
    ],
    webhookSupported: true,
    pollingFallback: false,
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "conn-fb",
    provider: "facebook",
    accountName: "SignalNest Official",
    accountId: "fb_page_559281",
    status: "disconnected",
    allowedScopes: ["pages_manage_posts", "pages_read_engagement", "pages_messaging"],
    encryptedTokenPlaceholder: "enc_vault_fb_page_382...ready",
    capabilities: [
      "Facebook Page status & link announcements",
      "Audience comment monitoring",
      "Messenger lead conversion workflow",
      "Meta Webhook hub signature validation",
    ],
    webhookSupported: true,
    pollingFallback: true,
  },
  {
    id: "conn-x",
    provider: "x",
    accountName: "@SignalNestApp",
    accountId: "tw_198273615",
    status: "disconnected",
    allowedScopes: ["tweet.read", "tweet.write", "users.read", "offline.access", "dm.read"],
    encryptedTokenPlaceholder: "enc_vault_x_pkce_094...ready",
    capabilities: [
      "280-character post & thread scheduling",
      "Mention stream monitoring & sentiment scoring",
      "Direct message triage",
      "X API v2 OAuth 2.0 PKCE with refresh token rotation",
    ],
    webhookSupported: false,
    pollingFallback: true,
  },
  {
    id: "conn-yt",
    provider: "youtube",
    accountName: "SignalNest Devs",
    accountId: "yt_ch_UC71829",
    status: "disconnected",
    allowedScopes: ["https://www.googleapis.com/auth/youtube.upload", "https://www.googleapis.com/auth/youtube.readonly"],
    encryptedTokenPlaceholder: "enc_vault_yt_gauth_11...ready",
    capabilities: [
      "Video upload metadata, chapters & tags staging",
      "Community tab post scheduling",
      "Comment sentiment analysis and reply approvals",
      "Official Google Cloud OAuth 2.0 integration",
    ],
    webhookSupported: true,
    pollingFallback: true,
  },
  {
    id: "conn-tt",
    provider: "tiktok",
    accountName: "@signalnest",
    accountId: "tt_open_44819",
    status: "disconnected",
    allowedScopes: ["user.info.basic", "video.upload", "video.publish"],
    encryptedTokenPlaceholder: "enc_vault_tt_oauth_88...ready",
    capabilities: [
      "Direct post staging with sound recommendations",
      "Creator marketplace video metadata orchestration",
      "TikTok Content Posting API official certification boundary",
    ],
    webhookSupported: true,
    pollingFallback: false,
  },
  {
    id: "conn-rd",
    provider: "reddit",
    accountName: "u/SignalNest_Dev",
    accountId: "rd_usr_7718",
    status: "disconnected",
    allowedScopes: ["identity", "submit", "read", "privatemessages"],
    encryptedTokenPlaceholder: "enc_vault_rd_tok_612...ready",
    capabilities: [
      "Subreddit tech discussion listening (r/webdev, r/saas, r/programming)",
      "Technical answer drafting with markdown formatting",
      "Moderator approval policy compliance",
    ],
    webhookSupported: false,
    pollingFallback: true,
  },
  {
    id: "conn-dc",
    provider: "discord",
    accountName: "SignalNest Bot #4891",
    accountId: "dc_bot_198273",
    status: "disconnected",
    allowedScopes: ["bot", "applications.commands", "messages.read"],
    encryptedTokenPlaceholder: "enc_vault_dc_bot_331...ready",
    capabilities: [
      "Community server VIP thread monitoring",
      "Moderation alerts & urgent sentiment dispatches",
      "Internal approval notification webhook bridge",
    ],
    webhookSupported: true,
    pollingFallback: true,
  },
  {
    id: "conn-tg",
    provider: "telegram",
    accountName: "@SignalNestAlertsBot",
    accountId: "tg_bot_88271",
    status: "disconnected",
    allowedScopes: ["getUpdates", "sendMessage"],
    encryptedTokenPlaceholder: "enc_vault_tg_bot_772...ready",
    capabilities: [
      "Instant executive emergency notifications",
      "Interactive 1-click Approval callbacks (Approve/Reject from phone)",
      "Long-polling and MTProto webhook gateway",
    ],
    webhookSupported: true,
    pollingFallback: true,
  },
  {
    id: "conn-sl",
    provider: "slack",
    accountName: "SignalNest Commander",
    accountId: "sl_bot_T0918_B712",
    status: "disconnected",
    allowedScopes: ["chat:write", "channels:read", "app_mentions:read"],
    encryptedTokenPlaceholder: "enc_vault_sl_bot_512...ready",
    capabilities: [
      "Internal team approval dispatch cards (Block Kit)",
      "High-priority lead escalation alerts",
      "Encrypted Slack signing secret request verification",
    ],
    webhookSupported: true,
    pollingFallback: false,
  },
];

export const initialEvents: SocialEvent[] = [
  {
    id: "evt-gh-1",
    source: "github",
    type: "PR",
    authorName: "Sarah Chen",
    authorHandle: "sarahc-dev",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    content: "Opened PR #142: 'Implement zero-trust OAuth token vault with AES-256-GCM encryption'. Requesting architectural review before we tag v1.2.",
    url: "https://github.com/mani-538/SignalNest/pull/142",
    priority: 95,
    sentiment: "positive",
    status: "needs_reply",
    suggestedReply: "Thanks @sarahc-dev! Great work on ensuring our encryption boundaries match the security brief. Reviewing the PR diff now—looks like the KMS key rotation hook is solid.",
    currentReplyDraft: "Thanks @sarahc-dev! Great work on ensuring our encryption boundaries match the security brief. Reviewing the PR diff now—looks like the KMS key rotation hook is solid.",
    aiSummary: "High-priority security pull request adding cryptographic token storage with zero-trust key rotation. Ready for Commander review.",
    occurredAt: "2026-09-24T10:14:00Z",
    tags: ["Security", "Architecture", "PR"],
  },
  {
    id: "evt-li-1",
    source: "linkedin",
    type: "COMMENT",
    authorName: "Marcus Vance",
    authorHandle: "marcusvance-vc",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    content: "Your latest breakdown on approval-first Social Media OS vs noisy auto-posters was spot on. Are you opening up early private alpha access for portfolio enterprise founders?",
    url: "https://linkedin.com/posts/signalnest_approval_os_8921",
    priority: 88,
    sentiment: "positive",
    status: "needs_reply",
    suggestedReply: "Appreciate the thoughtful feedback, Marcus! We're onboarding a small cohort of technical founders who manage multiple platforms. Dropping you a direct invite to the alpha portal.",
    currentReplyDraft: "Appreciate the thoughtful feedback, Marcus! We're onboarding a small cohort of technical founders who manage multiple platforms. Dropping you a direct invite to the alpha portal.",
    aiSummary: "Inbound venture capital / enterprise lead requesting private alpha access for portfolio companies.",
    occurredAt: "2026-09-24T11:42:00Z",
    tags: ["Investor", "Lead", "Alpha"],
  },
  {
    id: "evt-x-1",
    source: "x",
    type: "MENTION",
    authorName: "Alex Rivera",
    authorHandle: "@arivera_builds",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    content: "Testing @SignalNestApp architecture today. The fact that scheduled posts require explicit human sign-off before hitting social APIs is such a breath of fresh air. No more catastrophic AI hallucinations posting into the wild!",
    url: "https://x.com/arivera_builds/status/178921827419",
    priority: 82,
    sentiment: "positive",
    status: "needs_reply",
    suggestedReply: "Human-in-the-loop is our core philosophy, Alex! Speed with guardrails is how leaders protect their brand. Thanks for the shoutout!",
    currentReplyDraft: "Human-in-the-loop is our core philosophy, Alex! Speed with guardrails is how leaders protect their brand. Thanks for the shoutout!",
    aiSummary: "Public endorsement on X praising our human-in-the-loop approval design.",
    occurredAt: "2026-09-24T12:05:00Z",
    tags: ["Advocate", "Public Mention"],
  },
  {
    id: "evt-ig-1",
    source: "instagram",
    type: "DM",
    authorName: "Elena Rostova",
    authorHandle: "@elena.creative.agency",
    authorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    content: "Hello! We manage 14 client accounts across IG, TikTok, and LinkedIn. Can we enforce custom approval rules where junior copywriters draft but only our directors can approve?",
    url: "https://instagram.com/direct/t/882194819",
    priority: 76,
    sentiment: "positive",
    status: "needs_reply",
    suggestedReply: "Hi Elena! Yes, SignalNest has a dedicated RBAC approval system. You can define Commander and Reviewer roles so all public posts stay in 'Needs Approval' until authorized.",
    currentReplyDraft: "Hi Elena! Yes, SignalNest has a dedicated RBAC approval system. You can define Commander and Reviewer roles so all public posts stay in 'Needs Approval' until authorized.",
    aiSummary: "Agency prospect with 14 clients inquiring about multi-tiered role approval workflows.",
    occurredAt: "2026-09-24T12:30:00Z",
    tags: ["Agency", "Lead", "Direct Message"],
  },
  {
    id: "evt-gh-2",
    source: "github",
    type: "ISSUE",
    authorName: "David K.",
    authorHandle: "dk-infra",
    authorAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    content: "Issue #89: 'Support webhook signature rotation for GitHub Organization apps'. When GitHub rotates secrets, our verification handler should accept dual signatures during the transition window.",
    url: "https://github.com/mani-538/SignalNest/issues/89",
    priority: 70,
    sentiment: "neutral",
    status: "needs_reply",
    suggestedReply: "Good catch @dk-infra. We've added this to the webhook adapter milestone. We'll support an array of valid verification secrets in `verifyWebhookSignature`.",
    currentReplyDraft: "Good catch @dk-infra. We've added this to the webhook adapter milestone. We'll support an array of valid verification secrets in `verifyWebhookSignature`.",
    aiSummary: "Technical enhancement request for graceful webhook secret rotation handling in GitHub provider adapter.",
    occurredAt: "2026-09-24T13:10:00Z",
    tags: ["Enhancement", "Adapter", "GitHub"],
  },
  {
    id: "evt-fb-1",
    source: "facebook",
    type: "LEAD",
    authorName: "Liam O'Connor",
    authorHandle: "liam.oconnor.marketing",
    authorAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    content: "Inquiry on SignalNest Page: Is there an on-premise or self-hosted Docker compose option for European privacy compliance?",
    url: "https://facebook.com/messages/t/page_559281",
    priority: 65,
    sentiment: "neutral",
    status: "needs_reply",
    suggestedReply: "Hi Liam, SignalNest is built with PostgreSQL and Prisma with self-hosting in mind. All tokens stay in your private encrypted vault. Connecting you with our solutions engineer.",
    currentReplyDraft: "Hi Liam, SignalNest is built with PostgreSQL and Prisma with self-hosting in mind. All tokens stay in your private encrypted vault. Connecting you with our solutions engineer.",
    aiSummary: "Enterprise compliance inquiry regarding European self-hosting and token vault localization.",
    occurredAt: "2026-09-24T13:45:00Z",
    tags: ["Enterprise", "Self-Hosted", "Meta"],
  },
  {
    id: "evt-rd-1",
    source: "reddit",
    type: "COMMENT",
    authorName: "code_wanderer",
    authorHandle: "u/code_wanderer",
    authorAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    content: "Comment on r/webdev: 'What stack are you all using for multi-tenant webhook verification in Next.js App Router?'",
    url: "https://reddit.com/r/webdev/comments/182n9q/multi_tenant_webhooks",
    priority: 55,
    sentiment: "neutral",
    status: "draft_saved",
    suggestedReply: "We use edge-safe crypto verification inside `/api/webhooks/[provider]` routes with raw body buffers before passing normalized payloads into Prisma idempotency tables.",
    currentReplyDraft: "We use edge-safe crypto verification inside `/api/webhooks/[provider]` routes with raw body buffers before passing normalized payloads into Prisma idempotency tables.",
    aiSummary: "Technical discussion on Reddit regarding robust Next.js App Router webhook architecture.",
    occurredAt: "2026-09-24T14:15:00Z",
    tags: ["Community", "r/webdev"],
  },
  {
    id: "evt-dc-1",
    source: "discord",
    type: "MENTION",
    authorName: "Zack (Mod)",
    authorHandle: "@zack_dev_mod",
    authorAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    content: "Hey @Commander, community members are asking when the next GitHub Release Notes livestream is happening. Channel has 45 people waiting.",
    url: "https://discord.com/channels/198273/9921",
    priority: 60,
    sentiment: "neutral",
    status: "done",
    suggestedReply: "Hey Zack! Scheduled for this Friday at 3 PM UTC. Dropping the calendar link into the announcements channel now.",
    currentReplyDraft: "Hey Zack! Scheduled for this Friday at 3 PM UTC. Dropping the calendar link into the announcements channel now.",
    aiSummary: "Community moderator query regarding release notes livestream scheduling.",
    occurredAt: "2026-09-24T09:00:00Z",
    tags: ["Community", "Livestream"],
  },
];

export const initialContentItems: ContentItem[] = [
  {
    id: "cnt-1",
    coreIdea: "Why automated auto-posting tools kill organic tech credibility and how approval-first workflows save brands.",
    platform: "linkedin",
    title: "The Death of Blind Social Automation",
    draft: `Most social media tools treat your audience like a pipeline for auto-generated noise.\n\nHere is what happens when you automate blindly:\n1. Tone-deaf replies during major industry incidents\n2. Hallucinated release notes that confuse your users\n3. Engagement that sounds like an out-of-touch bot\n\nThat's why we built SignalNest on an approval-first architecture.\n\nAI generates the draft. It suggests the angle. It checks the tone.\n\nBut the final push of the button? Always human.\n\nWhat is your team's policy on public brand posting? Do you require human sign-off?`,
    status: "scheduled",
    scheduledAt: "2026-09-25T14:00:00Z",
    tone: "Thought Leadership",
    targetAudience: "Engineering leaders & tech founders",
    hashtags: ["#BuildingInPublic", "#DevTools", "#SocialOS", "#SoftwareEngineering"],
    cta: "Drop your perspective in the comments below.",
    objective: "Establish thought leadership around approval-first human-in-the-loop social management.",
    characterLimit: 3000,
    createdAt: "2026-09-24T08:00:00Z",
    updatedAt: "2026-09-24T14:30:00Z",
  },
  {
    id: "cnt-2",
    coreIdea: "Announcing SignalNest v1.0 architecture with zero-scraping official OAuth boundaries.",
    platform: "x",
    title: "SignalNest v1.0 Launch Tweet",
    draft: `Today we're open-sourcing the design for SignalNest: a single command center for personal social operations.\n\n✓ Zero browser scraping\n✓ Zero hardcoded passwords\n✓ 100% official OAuth & webhook boundaries\n✓ Mandatory human approval queue\n\nTake control of your signal: signalnest.dev`,
    status: "approved",
    scheduledAt: "2026-09-25T16:30:00Z",
    tone: "Punchy",
    targetAudience: "Developers & indie hackers",
    hashtags: ["#buildinpublic", "#opensource", "#nextjs"],
    cta: "Take control of your signal: signalnest.dev",
    characterLimit: 280,
    createdAt: "2026-09-24T09:15:00Z",
    updatedAt: "2026-09-24T12:00:00Z",
  },
  {
    id: "cnt-3",
    coreIdea: "Release Notes for SignalNest Core v1.1.0 with provider adapter registry.",
    platform: "github",
    title: "v1.1.0: Enterprise Provider Adapters & Audit Log Engine",
    draft: `## SignalNest v1.1.0 Release Notes\n\n### 🚀 New Features\n- **Provider Adapter Architecture**: Added unified interfaces for GitHub, LinkedIn, Meta, X, and YouTube.\n- **Mandatory Approval Queue**: All public publish requests generate an immutable audit log entry before dispatch.\n- **Unified Inbox Stream**: Aggregate mentions, PRs, comments, and DMs into a prioritized triage feed.\n\n### 🛡️ Security & Reliability\n- Zero-trust token vault structure ready for KMS envelope encryption.\n- Idempotency tokens on all scheduled actions.\n- Webhook cryptographic signature verification helpers.\n\n### 📦 How to upgrade\n\`npm install @signalnest/core@1.1.0\``,
    status: "needs_approval",
    scheduledAt: "2026-09-26T17:00:00Z",
    tone: "Technical",
    targetAudience: "Open source contributors & technical users",
    hashtags: ["#release", "#v1_1_0"],
    cta: "Check out the full diff on GitHub.",
    characterLimit: 10000,
    createdAt: "2026-09-24T11:00:00Z",
    updatedAt: "2026-09-24T11:00:00Z",
  },
  {
    id: "cnt-4",
    coreIdea: "Behind-the-scenes visual look at the dark-mode command center UI.",
    platform: "instagram",
    title: "Behind the Screens: The Dark Mode Command Center",
    draft: `Building software shouldn't feel like wrestling with noisy spreadsheets.\n\nHere's our dark-mode first command dashboard for SignalNest: built with deep charcoal tones, restrained indigo accents, and clear status signals.\n\nEvery incoming PR, DM, or mention gets scored and queued for one-tap review.\n\nWould you use a unified inbox for your developer presence? 👇\n\n.\n.\n.\n#devtools #darkmode #uiux #dashboarddesign #nextjs #codinglife #fullstack #indiedev #saasfounder #buildinpublic`,
    status: "draft",
    scheduledAt: "2026-09-27T18:00:00Z",
    tone: "Casual",
    targetAudience: "Designers & developers on Instagram",
    hashtags: ["#devtools", "#darkmode", "#uiux", "#nextjs", "#buildinpublic"],
    cta: "Comment your favorite UI palette below!",
    characterLimit: 2200,
    createdAt: "2026-09-24T13:00:00Z",
    updatedAt: "2026-09-24T13:00:00Z",
  },
  {
    id: "cnt-5",
    coreIdea: "Explaining how webhook verification prevents replay attacks in social apps.",
    platform: "youtube",
    title: "How We Protect Webhooks in Next.js App Router (Full Code Walkthrough)",
    draft: `In this deep-dive walkthrough, we explore how to verify cryptographic signatures from GitHub, Slack, and Meta without buffering memory leaks in serverless functions.\n\nTimestamps:\n00:00 - The Problem with Naive Webhook Endpoints\n02:15 - Understanding HMAC-SHA256 Signatures\n05:40 - Implementing Raw Body Buffering in App Router\n09:12 - Idempotency Keys & Deduplication in Prisma\n14:30 - Live Testing with ngrok\n\nLinks mentioned in this video are in the pinned comment.`,
    status: "idea",
    scheduledAt: "2026-09-28T15:00:00Z",
    tone: "Educational",
    targetAudience: "Full stack TypeScript developers",
    hashtags: ["#nextjs", "#webhooks", "#security", "#typescript"],
    cta: "Subscribe for more deep-dive systems engineering walkthroughs.",
    characterLimit: 5000,
    createdAt: "2026-09-24T13:45:00Z",
    updatedAt: "2026-09-24T13:45:00Z",
  },
  {
    id: "cnt-6",
    coreIdea: "Quick 30-second coding tip on type-safe environment variables with Zod.",
    platform: "tiktok",
    title: "Never ship undefined env vars again",
    draft: `Stop writing process.env.API_KEY and hoping it exists! 🛑\n\nHere is how we use Zod to validate all 11 social provider secrets at startup. If a secret is missing, Next.js fails fast during build, not at 3 AM in production.\n\nCode snippet is in our bio! Follow for more full-stack hacks.`,
    status: "draft",
    scheduledAt: "2026-09-29T19:00:00Z",
    tone: "Punchy",
    targetAudience: "Junior to mid developers learning modern best practices",
    hashtags: ["#coding", "#programmer", "#javascript", "#typescript", "#techtok"],
    cta: "Check bio link for free starter template.",
    characterLimit: 2200,
    createdAt: "2026-09-24T14:10:00Z",
    updatedAt: "2026-09-24T14:10:00Z",
  },
];

export const initialAnalyticsSnapshots: AnalyticsSnapshot[] = [
  { date: "2026-09-18", platform: "all", followersTotal: 12450, followersDelta: 85, impressions: 38200, reach: 24100, engagements: 2150, engagementRate: 5.6, shares: 142 },
  { date: "2026-09-19", platform: "all", followersTotal: 12560, followersDelta: 110, impressions: 41900, reach: 26800, engagements: 2480, engagementRate: 5.9, shares: 189 },
  { date: "2026-09-20", platform: "all", followersTotal: 12640, followersDelta: 80, impressions: 36700, reach: 22900, engagements: 1980, engagementRate: 5.4, shares: 121 },
  { date: "2026-09-21", platform: "all", followersTotal: 12790, followersDelta: 150, impressions: 52100, reach: 33400, engagements: 3410, engagementRate: 6.5, shares: 284 },
  { date: "2026-09-22", platform: "all", followersTotal: 12920, followersDelta: 130, impressions: 48900, reach: 31200, engagements: 3100, engagementRate: 6.3, shares: 210 },
  { date: "2026-09-23", platform: "all", followersTotal: 13080, followersDelta: 160, impressions: 59400, reach: 38700, engagements: 4120, engagementRate: 6.9, shares: 340 },
  { date: "2026-09-24", platform: "all", followersTotal: 13240, followersDelta: 160, impressions: 64200, reach: 41800, engagements: 4680, engagementRate: 7.2, shares: 395 },
];

export const initialNotificationRules: NotificationRule[] = [
  { id: "nr-1", name: "High Priority Inbox Activity", condition: "HIGH_PRIORITY_INBOX", channel: "IN_APP", isEnabled: true },
  { id: "nr-2", name: "GitHub Pull Request Triage", condition: "NEW_PR", channel: "SLACK", channelTarget: "#dev-approvals", isEnabled: true },
  { id: "nr-3", name: "Urgent Sentiment Mentions", condition: "SENTIMENT_URGENT", channel: "TELEGRAM", channelTarget: "@CommanderBot", isEnabled: true },
  { id: "nr-4", name: "Public Post Approval Required", condition: "APPROVAL_REQUIRED", channel: "EMAIL", channelTarget: "commander@signalnest.dev", isEnabled: true },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    action: "SYSTEM_INITIALIZED",
    resourceType: "Settings",
    resourceId: "workspace-1",
    description: "SignalNest Command Center initialized in approval-first mode with 11 provider adapters.",
    actor: "Mani Shankar (Commander)",
    timestamp: "2026-09-24T08:00:00Z",
  },
  {
    id: "log-2",
    action: "DRAFT_SAVED",
    resourceType: "ContentItem",
    resourceId: "cnt-1",
    description: "Generated LinkedIn thought leadership draft: 'The Death of Blind Social Automation'.",
    actor: "Mani Shankar (Commander)",
    timestamp: "2026-09-24T08:45:00Z",
  },
  {
    id: "log-3",
    action: "POST_APPROVED",
    resourceType: "ContentItem",
    resourceId: "cnt-2",
    description: "Approved X launch announcement for scheduled dispatch.",
    actor: "Mani Shankar (Commander)",
    timestamp: "2026-09-24T12:00:00Z",
  },
  {
    id: "log-4",
    action: "REPLY_DRAFT_UPDATED",
    resourceType: "SocialEvent",
    resourceId: "evt-gh-1",
    description: "Updated suggested response for Sarah Chen's PR #142 zero-trust token vault.",
    actor: "Mani Shankar (Commander)",
    timestamp: "2026-09-24T12:15:00Z",
  },
];

export const defaultBrandSettings: BrandSettings = {
  userName: "Mani Shankar",
  userEmail: "commander@signalnest.dev",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  timezone: "UTC+05:30 (India Standard Time)",
  brandVoice: "Authoritative, technically precise, calm, and visionary. We avoid hype, buzzwords, and hollow marketing jargon. We speak directly to builders, engineers, and ambitious founders.",
  writingTone: "Thought Leadership",
  bannedTopics: [
    "Unverified crypto shilling",
    "Political debates",
    "Low-effort ragebait",
    "Unreviewed marketing claims",
  ],
  approvalPolicy: {
    alwaysRequireApprovalForReplies: true,
    alwaysRequireApprovalForPublishing: true,
    notifyOnHighPriority: true,
    dualReviewForExecutivePosts: false,
  },
};
